import type { Product } from "./types";

// Fallback catalogue used when the Django API is unavailable or returns nothing.
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo1",
    name: "Tomato, Pectomech",
    crop_type: "Tomato",
    price_per_unit: 380,
    unit: "crate",
    quantity_available: 180,
    sold_quantity: 40,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/tomatoes.jpg",
    description: "Crates of Pectomech tomatoes. Harvested and packed at the farm gate.",
  },
  {
    id: "demo2",
    name: "Maize, white",
    crop_type: "Maize",
    price_per_unit: 420,
    unit: "100kg bag",
    quantity_available: 500,
    sold_quantity: 120,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/maize.jpg",
    description: "Dried white maize in 100kg bags for grain traders, millers and feed processors.",
  },
  {
    id: "demo3",
    name: "Mango, Kent",
    crop_type: "Mango",
    price_per_unit: 110,
    unit: "box",
    quantity_available: 250,
    sold_quantity: 65,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/mango.jpg",
    description: "Hand-picked Kent mangoes sorted into boxes for market vendors and retailers.",
  },
  {
    id: "demo4",
    name: "Plantain, Apantu",
    crop_type: "Plantain",
    price_per_unit: 65,
    unit: "bunch",
    quantity_available: 350,
    sold_quantity: 80,
    min_order: 4,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/plantain.jpg",
    description: "Green Apantu plantain bunches harvested from farmer groups in the Eastern Region.",
  },
  {
    id: "demo5",
    name: "Yam, Puna",
    crop_type: "Yam",
    price_per_unit: 1800,
    unit: "100 tubers",
    quantity_available: 80,
    sold_quantity: 15,
    min_order: 1,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/tomatoes.jpg",
    description: "Puna yam tubers bundled in 100-tuber lots for bulk buyers and institutions.",
  },
  {
    id: "demo6",
    name: "Maize, white (Preorder)",
    crop_type: "Maize",
    price_per_unit: 390,
    unit: "100kg bag",
    quantity_available: 800,
    sold_quantity: 150,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: true,
    available_date: "2026-10-15",
    image_url: "/images/maize.jpg",
    description: "Preorder upcoming white maize harvest from farmer groups in the Eastern Region.",
  },
  {
    id: "demo7",
    name: "Eggs, medium",
    crop_type: "Poultry",
    price_per_unit: 62,
    unit: "crate",
    quantity_available: 300,
    sold_quantity: 50,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/eggs.jpg",
    description: "Farm eggs, 30 per crate, from layer farms in the Eastern Region.",
  },
  {
    id: "demo8",
    name: "Beef, cut",
    crop_type: "Beef",
    price_per_unit: 85,
    unit: "kg",
    quantity_available: 400,
    sold_quantity: 80,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/beef.jpg",
    description: "Beef cuts, chilled and packed for kitchens and retailers in the Eastern Region.",
  },
  {
    id: "demo9",
    name: "Goat meat",
    crop_type: "Goat",
    price_per_unit: 90,
    unit: "kg",
    quantity_available: 250,
    sold_quantity: 40,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/goat-meat.jpg",
    description: "Goat meat, cut and packed. No live animals.",
  },
  {
    id: "demo10",
    name: "Chicken meat",
    crop_type: "Poultry",
    price_per_unit: 75,
    unit: "kg",
    quantity_available: 200,
    sold_quantity: 30,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/chicken-meat.jpg",
    description: "Chicken meat, cleaned and packed for pilot delivery. Not live birds.",
  },
];
