import type { Product } from "./types";

// Fallback catalogue used when Supabase is not configured or returns nothing.
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo1",
    name: "Fresh Tomatoes — Grade A",
    crop_type: "Tomato",
    price_per_unit: 120,
    unit: "crate",
    quantity_available: 200,
    sold_quantity: 45,
    min_order: 5,
    region: "Ashanti",
    fbo_source: "Ejisu Farmers Cooperative",
    status: "available",
    is_preorder: false,
    image_url: "/images/tomatoes.jpg",
    description:
      "Premium Grade A tomatoes, freshly harvested. Perfect for wholesale and restaurant supply.",
  },
  {
    id: "demo2",
    name: "White Maize — Dried & Bagged",
    crop_type: "Maize",
    price_per_unit: 85,
    unit: "bag",
    quantity_available: 500,
    sold_quantity: 120,
    min_order: 2,
    region: "Bono / Brong-Ahafo",
    fbo_source: "Techiman FBO Group",
    status: "available",
    is_preorder: false,
    image_url: "/images/maize.jpg",
    description:
      "Certified dried white maize, 100kg bags. Ideal for flour mills, animal feed and trading.",
  },
  {
    id: "demo3",
    name: "Sweet Mango — Kent Variety",
    crop_type: "Mango",
    price_per_unit: 95,
    unit: "box",
    quantity_available: 300,
    sold_quantity: 80,
    min_order: 3,
    region: "Volta",
    fbo_source: "Ho Farmers Association",
    status: "available",
    is_preorder: false,
    image_url: "/images/mango.jpg",
    description:
      "Premium Kent mangoes, export quality. Sweet, large and freshly harvested from Volta Region farms.",
  },
  {
    id: "demo4",
    name: "Green Plantain — Apem",
    crop_type: "Plantain",
    price_per_unit: 55,
    unit: "bunch",
    quantity_available: 400,
    sold_quantity: 95,
    min_order: 4,
    region: "Eastern",
    fbo_source: "Suhum Plantain Growers FBO",
    status: "available",
    is_preorder: false,
    image_url: "/images/plantain.jpg",
    description:
      "Fresh green Apem plantains. Great for chips, boiling and fufu. Consistent size and quality.",
  },
  {
    id: "demo5",
    name: "Mixed Market Vegetables Bundle",
    crop_type: "Vegetables",
    price_per_unit: 150,
    unit: "bundle",
    quantity_available: 100,
    sold_quantity: 20,
    min_order: 1,
    region: "Greater Accra",
    fbo_source: "Accra Urban Farmers Coop",
    status: "available",
    is_preorder: false,
    image_url: "/images/market.jpg",
    description:
      "Weekly bundle of fresh market vegetables. Includes seasonal produce sourced directly from farms.",
  },
  {
    id: "demo6",
    name: "Maize (Preorder) — October Harvest",
    crop_type: "Maize",
    price_per_unit: 80,
    unit: "bag",
    quantity_available: 1000,
    sold_quantity: 200,
    min_order: 5,
    region: "Northern",
    fbo_source: "Tamale Grain Farmers FBO",
    status: "available",
    is_preorder: true,
    available_date: "2026-10-15",
    image_url: "/images/maize.jpg",
    description:
      "Preorder next harvest season's white maize from the Northern Region. Lock in your price today.",
  },
];
