import type { Product } from "./types";

// Fallback catalogue used when the Django API is unavailable or returns nothing.
export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo1",
    name: "Tomato, Pectomech",
    crop_type: "Tomato",
    price_per_unit: 380,
    unit: "crate",
    quantity_available: 180,
    sold_quantity: 40,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/tomatoes.webp",
    description: "Crates of Pectomech tomatoes. Harvested and packed at the farm gate.",
  },
  {
    id: "demo2",
    name: "Maize, yellow",
    crop_type: "Maize",
    price_per_unit: 420,
    unit: "cob",
    quantity_available: 500,
    sold_quantity: 120,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/maize.webp",
    description: "Yellow maize cobs from farmer groups in the Eastern Region.",
  },
  {
    id: "demo3",
    name: "Mango, Kent",
    crop_type: "Mango",
    price_per_unit: 110,
    unit: "box",
    quantity_available: 250,
    sold_quantity: 65,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/mango.webp",
    description: "Hand-picked Kent mangoes sorted into boxes for market vendors and retailers.",
  },
  {
    id: "demo4",
    name: "Plantain, Apantu",
    crop_type: "Plantain",
    price_per_unit: 65,
    unit: "bunch",
    quantity_available: 350,
    sold_quantity: 80,
    min_order: 4,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/plantain.webp",
    description: "Green Apantu plantain bunches harvested from farmer groups in the Eastern Region.",
  },
  {
    id: "demo5",
    name: "Yam, Puna",
    crop_type: "Yam",
    price_per_unit: 1800,
    unit: "100 tubers",
    quantity_available: 80,
    sold_quantity: 15,
    min_order: 1,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/yam.webp",
    description: "Puna yam tubers from farmer groups in the Eastern Region.",
  },
  {
    id: "demo7",
    name: "Eggs, medium",
    crop_type: "Poultry",
    price_per_unit: 62,
    unit: "crate",
    quantity_available: 300,
    sold_quantity: 50,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/eggs.webp",
    description: "Farm eggs, 30 per crate, from layer farms in the Eastern Region.",
  },
  {
    id: "demo8",
    name: "Beef, cut",
    crop_type: "Beef",
    price_per_unit: 85,
    unit: "kg",
    quantity_available: 400,
    sold_quantity: 80,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/beef.webp",
    description: "Beef cuts, chilled and packed for kitchens and retailers in the Eastern Region.",
  },
  {
    id: "demo9",
    name: "Goat meat",
    crop_type: "Goat",
    price_per_unit: 90,
    unit: "kg",
    quantity_available: 250,
    sold_quantity: 40,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/goat-meat.webp",
    description: "Goat meat, cut and packed. No live animals.",
  },
  {
    id: "demo10",
    name: "Chicken meat",
    crop_type: "Poultry",
    price_per_unit: 75,
    unit: "kg",
    quantity_available: 200,
    sold_quantity: 30,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/chicken-meat.webp",
    description: "Chicken meat, cleaned and packed for pilot delivery. Not live birds.",
  },
  {
    id: "demo11",
    name: "Pork, shoulder cuts",
    crop_type: "Pork",
    price_per_unit: 95,
    unit: "kg",
    quantity_available: 150,
    sold_quantity: 25,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/pork.webp",
    description: "Fresh pork shoulder cuts from certified farms in the Eastern Region.",
  },
  {
    id: "demo12",
    name: "Guinea fowl meat",
    crop_type: "Poultry",
    price_per_unit: 110,
    unit: "kg",
    quantity_available: 80,
    sold_quantity: 15,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/guinea-fowl.webp",
    description: "Roasted guinea fowl meat from farms in the Eastern Region.",
  },
  {
    id: "demo13",
    name: "Smoked catfish",
    crop_type: "Fish",
    price_per_unit: 65,
    unit: "kg",
    quantity_available: 120,
    sold_quantity: 35,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/smoked-fish.webp",
    description: "Smoked catfish, ready to cook. Traditional smoking methods from Eastern Region.",
  },
  {
    id: "demo14",
    name: "Fresh tilapia fillets",
    crop_type: "Fish",
    price_per_unit: 55,
    unit: "kg",
    quantity_available: 90,
    sold_quantity: 20,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/tilapia.webp",
    description: "Fresh tilapia fish fillets from fish farms in the Eastern Region.",
  },
  {
    id: "demo15",
    name: "Wild honey",
    crop_type: "Honey",
    price_per_unit: 280,
    unit: "bottle (750ml)",
    quantity_available: 45,
    sold_quantity: 12,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/honey.webp",
    description: "Pure wild honey harvested from beekeepers in the Eastern Region.",
  },
  {
    id: "demo16",
    name: "Mutton cuts",
    crop_type: "Mutton",
    price_per_unit: 105,
    unit: "kg",
    quantity_available: 70,
    sold_quantity: 18,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "available",
    is_preorder: false,
    image_url: "/images/mutton.webp",
    description: "Fresh mutton cuts from sheep farms in the Eastern Region.",
  },
  {
    id: "demo17",
    name: "Coconut, dry",
    crop_type: "Coconut",
    price_per_unit: 180,
    unit: "sack",
    quantity_available: 90,
    sold_quantity: 8,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-12-01",
    image_url: "/images/coconut.webp",
    description: "Dry brown coconuts from farmer groups in the Eastern Region. Reserve the lot before harvest.",
  },
  {
    id: "demo18",
    name: "Pepper, scotch bonnet",
    crop_type: "Pepper",
    price_per_unit: 95,
    unit: "bag",
    quantity_available: 140,
    sold_quantity: 12,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-11-15",
    image_url: "/images/pepper.webp",
    description: "Hot scotch bonnet pepper from Eastern Region farms. Lock grade and quantity before the harvest.",
  },
  {
    id: "demo19",
    name: "Pineapple, Smooth Cayenne",
    crop_type: "Pineapple",
    price_per_unit: 140,
    unit: "crate",
    quantity_available: 160,
    sold_quantity: 20,
    min_order: 4,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-10-20",
    image_url: "/images/pineapple.webp",
    description: "Smooth Cayenne pineapples from Eastern Region groups. Pre-order for the coming harvest.",
  },
  {
    id: "demo20",
    name: "Orange, Valencia",
    crop_type: "Orange",
    price_per_unit: 85,
    unit: "bag",
    quantity_available: 200,
    sold_quantity: 18,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-12-10",
    image_url: "/images/orange.webp",
    description: "Valencia oranges from citrus farms in the Eastern Region. Reserve before picking.",
  },
  {
    id: "demo21",
    name: "Pawpaw, Red Lady",
    crop_type: "Pawpaw",
    price_per_unit: 70,
    unit: "crate",
    quantity_available: 110,
    sold_quantity: 10,
    min_order: 3,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-11-01",
    image_url: "/images/pawpaw.webp",
    description: "Red Lady pawpaw from Eastern Region orchards. Buyers lock quantity before harvest.",
  },
  {
    id: "demo22",
    name: "Banana, Cavendish",
    crop_type: "Banana",
    price_per_unit: 45,
    unit: "bunch",
    quantity_available: 220,
    sold_quantity: 25,
    min_order: 5,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2026-10-15",
    image_url: "/images/banana.webp",
    description: "Cavendish banana bunches from farmer groups in the Eastern Region. Pre-order the coming cut.",
  },
  {
    id: "demo23",
    name: "Watermelon, Sugar Baby",
    crop_type: "Watermelon",
    price_per_unit: 55,
    unit: "crate",
    quantity_available: 95,
    sold_quantity: 6,
    min_order: 2,
    region: "Eastern",
    fbo_source: "FBO onboarding — Eastern",
    status: "preorder",
    is_preorder: true,
    available_date: "2027-01-10",
    image_url: "/images/watermelon.webp",
    description: "Sugar Baby watermelon from Eastern Region plots. Reserve grade and count before harvest.",
  },
];
