from decimal import Decimal
from datetime import timedelta

from django.core.files.base import ContentFile
from django.core.management.base import BaseCommand
from django.utils import timezone

from marketplace.models import Order, PageView, Product


DEMO = [
    {
        "name": "Tomato, Pectomech",
        "crop_type": "Tomato",
        "price": "380.00",
        "unit": "crate",
        "qty": 180,
        "sold": 40,
        "min_order": 5,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244123456",
        "desc": "Crates of Pectomech tomatoes. Harvested and packed at the farm gate.",
        "image": "tomatoes.webp",
    },
    {
        "name": "Maize, yellow",
        "crop_type": "Maize",
        "price": "420.00",
        "unit": "cob",
        "qty": 500,
        "sold": 120,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244555666",
        "desc": "Yellow maize cobs from farmer groups in the Eastern Region.",
        "image": "maize.webp",
    },
    {
        "name": "Mango, Kent",
        "crop_type": "Mango",
        "price": "110.00",
        "unit": "box",
        "qty": 250,
        "sold": 65,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244777888",
        "desc": "Hand-picked Kent mangoes sorted into boxes.",
        "image": "mango.webp",
    },
    {
        "name": "Plantain, Apantu",
        "crop_type": "Plantain",
        "price": "65.00",
        "unit": "bunch",
        "qty": 350,
        "sold": 80,
        "min_order": 4,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244999000",
        "desc": "Green Apantu plantain bunches.",
        "image": "plantain.webp",
    },
    {
        "name": "Yam, Puna",
        "crop_type": "Yam",
        "price": "1800.00",
        "unit": "100 tubers",
        "qty": 80,
        "sold": 15,
        "min_order": 1,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244000111",
        "desc": "Puna yam tubers from farmer groups in the Eastern Region.",
        "image": "yam.webp",
    },
    {
        "name": "Eggs, medium",
        "crop_type": "Poultry",
        "price": "62.00",
        "unit": "crate",
        "qty": 300,
        "sold": 50,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244333444",
        "desc": "Farm eggs, 30 per crate.",
        "image": "eggs.webp",
    },
    {
        "name": "Beef, cut",
        "crop_type": "Beef",
        "price": "85.00",
        "unit": "kg",
        "qty": 400,
        "sold": 80,
        "min_order": 5,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244555777",
        "desc": "Beef cuts, chilled and packed.",
        "image": "beef.webp",
    },
    {
        "name": "Goat meat",
        "crop_type": "Goat",
        "price": "90.00",
        "unit": "kg",
        "qty": 250,
        "sold": 40,
        "min_order": 5,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244666888",
        "desc": "Goat meat. Not a live animal.",
        "image": "goat-meat.webp",
    },
    {
        "name": "Chicken meat",
        "crop_type": "Poultry",
        "price": "75.00",
        "unit": "kg",
        "qty": 200,
        "sold": 30,
        "min_order": 5,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244888999",
        "desc": "Chicken meat, cleaned and packed. Not live birds.",
        "image": "chicken-meat.webp",
    },
    {
        "name": "Pork, shoulder cuts",
        "crop_type": "Pork",
        "price": "95.00",
        "unit": "kg",
        "qty": 150,
        "sold": 25,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244112233",
        "desc": "Fresh pork shoulder cuts from certified farms in the Eastern Region.",
        "image": "pork.webp",
    },
    {
        "name": "Guinea fowl meat",
        "crop_type": "Poultry",
        "price": "110.00",
        "unit": "kg",
        "qty": 80,
        "sold": 15,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244334455",
        "desc": "Roasted guinea fowl meat from farms in the Eastern Region.",
        "image": "guinea-fowl.webp",
    },
    {
        "name": "Smoked catfish",
        "crop_type": "Fish",
        "price": "65.00",
        "unit": "kg",
        "qty": 120,
        "sold": 35,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244556677",
        "desc": "Smoked catfish, ready to cook. Traditional smoking methods from Eastern Region.",
        "image": "smoked-fish.webp",
    },
    {
        "name": "Fresh tilapia fillets",
        "crop_type": "Fish",
        "price": "55.00",
        "unit": "kg",
        "qty": 90,
        "sold": 20,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244778899",
        "desc": "Fresh tilapia fish fillets from fish farms in the Eastern Region.",
        "image": "tilapia.webp",
    },
    {
        "name": "Wild honey",
        "crop_type": "Honey",
        "price": "280.00",
        "unit": "bottle (750ml)",
        "qty": 45,
        "sold": 12,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244990011",
        "desc": "Pure wild honey harvested from beekeepers in the Eastern Region.",
        "image": "honey.webp",
    },
    {
        "name": "Mutton cuts",
        "crop_type": "Mutton",
        "price": "105.00",
        "unit": "kg",
        "qty": 70,
        "sold": 18,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244123789",
        "desc": "Fresh mutton cuts from sheep farms in the Eastern Region.",
        "image": "mutton.webp",
    },
    {
        "name": "Coconut, dry",
        "crop_type": "Coconut",
        "price": "180.00",
        "unit": "sack",
        "qty": 90,
        "sold": 8,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244234567",
        "desc": "Dry brown coconuts from farmer groups in the Eastern Region. Reserve the lot before harvest.",
        "image": "coconut.webp",
        "preorder": True,
        "available": "2026-12-01",
    },
    {
        "name": "Pepper, scotch bonnet",
        "crop_type": "Pepper",
        "price": "95.00",
        "unit": "bag",
        "qty": 140,
        "sold": 12,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244345678",
        "desc": "Hot scotch bonnet pepper from Eastern Region farms. Lock grade and quantity before the harvest.",
        "image": "pepper.webp",
        "preorder": True,
        "available": "2026-11-15",
    },
    {
        "name": "Pineapple, Smooth Cayenne",
        "crop_type": "Pineapple",
        "price": "140.00",
        "unit": "crate",
        "qty": 160,
        "sold": 20,
        "min_order": 4,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244456789",
        "desc": "Smooth Cayenne pineapples from Eastern Region groups. Pre-order for the coming harvest.",
        "image": "pineapple.webp",
        "preorder": True,
        "available": "2026-10-20",
    },
    {
        "name": "Orange, Valencia",
        "crop_type": "Orange",
        "price": "85.00",
        "unit": "bag",
        "qty": 200,
        "sold": 18,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244567890",
        "desc": "Valencia oranges from citrus farms in the Eastern Region. Reserve before picking.",
        "image": "orange.webp",
        "preorder": True,
        "available": "2026-12-10",
    },
    {
        "name": "Pawpaw, Red Lady",
        "crop_type": "Pawpaw",
        "price": "70.00",
        "unit": "crate",
        "qty": 110,
        "sold": 10,
        "min_order": 3,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244678901",
        "desc": "Red Lady pawpaw from Eastern Region orchards. Buyers lock quantity before harvest.",
        "image": "pawpaw.webp",
        "preorder": True,
        "available": "2026-11-01",
    },
    {
        "name": "Banana, Cavendish",
        "crop_type": "Banana",
        "price": "45.00",
        "unit": "bunch",
        "qty": 220,
        "sold": 25,
        "min_order": 5,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244789012",
        "desc": "Cavendish banana bunches from farmer groups in the Eastern Region. Pre-order the coming cut.",
        "image": "banana.webp",
        "preorder": True,
        "available": "2026-10-15",
    },
    {
        "name": "Watermelon, Sugar Baby",
        "crop_type": "Watermelon",
        "price": "55.00",
        "unit": "crate",
        "qty": 95,
        "sold": 6,
        "min_order": 2,
        "region": "Eastern",
        "fbo": "Eastern FBO",
        "phone": "0244890123",
        "desc": "Sugar Baby watermelon from Eastern Region plots. Reserve grade and count before harvest.",
        "image": "watermelon.webp",
        "preorder": True,
        "available": "2027-01-10",
    },
]


class Command(BaseCommand):
    help = "Seed demo products and a few sample orders for the admin analytics view."

    def handle(self, *args, **options):
        from pathlib import Path
        from django.conf import settings

        created = 0
        products = []
        image_roots = [
            Path(settings.BASE_DIR).parent / "public" / "images",
        ]

        for item in DEMO:
            obj, was_created = Product.objects.get_or_create(
                name=item["name"],
                defaults={
                    "crop_type": item["crop_type"],
                    "price_per_unit": Decimal(item["price"]),
                    "unit": item["unit"],
                    "quantity_available": item["qty"],
                    "sold_quantity": item["sold"],
                    "min_order": item["min_order"],
                    "region": item["region"],
                    "fbo_source": item["fbo"],
                    "farmer_phone": item["phone"],
                    "description": item["desc"],
                    "is_preorder": bool(item.get("preorder")),
                    "available_date": item.get("available"),
                    "status": Product.Status.PREORDER if item.get("preorder") else Product.Status.AVAILABLE,
                },
            )
            if was_created:
                created += 1
                img_name = item["image"]
                for root in image_roots:
                    src = root / img_name
                    if src.exists():
                        obj.image.save(img_name, ContentFile(src.read_bytes()), save=True)
                        break
            products.append(obj)

        if products and not Order.objects.exists():
            tomato = products[0]
            maize = products[1]
            now = timezone.now()
            samples = [
                (tomato, 8, "paid", "delivered", 6),
                (tomato, 5, "paid", "dispatched", 3),
                (maize, 12, "paid", "confirmed", 1),
                (products[2], 4, "pending", "pending", 0),
            ]
            for i, (prod, qty, pay, ost, days_ago) in enumerate(samples, start=1):
                subtotal = prod.price_per_unit * qty
                delivery = Decimal("30.00")
                Order.objects.create(
                    order_ref=f"AGB-2026-{1000 + i}",
                    product=prod,
                    product_name=prod.name,
                    product_unit=prod.unit,
                    buyer_name=["Ama Boateng", "Kwame Mensah", "Akosua Darko", "Yaw Asante"][i - 1],
                    buyer_phone=["0244111222", "0244333444", "0244555666", "0244777888"][i - 1],
                    buyer_email="buyer@harvestgh.com",
                    quantity=qty,
                    price_per_unit=prod.price_per_unit,
                    subtotal=subtotal,
                    delivery_fee=delivery,
                    total_price=subtotal + delivery,
                    delivery_address="East Legon, Accra",
                    delivery_region="Eastern",
                    payment_status=pay,
                    payment_ref=f"PSK-{i}",
                    order_status=ost,
                    created_at=now - timedelta(days=days_ago),
                )
            # auto_now_add ignores created_at on insert in some Django versions — force timestamps
            for i, days_ago in enumerate([6, 3, 1, 0], start=1):
                Order.objects.filter(order_ref=f"AGB-2026-{1000 + i}").update(
                    created_at=now - timedelta(days=days_ago)
                )

        for path, hits in [("/", 42), ("/shop", 31), ("/about", 12), ("/contact", 8)]:
            PageView.objects.get_or_create(
                path=path,
                viewed_on=timezone.localdate(),
                defaults={"count": hits},
            )

        self.stdout.write(self.style.SUCCESS(f"Seeded {created} new products (total {Product.objects.count()})."))
