# Generated by Django 5.2.17 on 2026-09-22 03:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Buyer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("business_name", models.CharField(blank=True, max_length=160)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("region", models.CharField(max_length=80)),
                ("buyer_type", models.CharField(max_length=80)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Buyers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("phone", models.CharField(max_length=20)),
                ("role", models.CharField(blank=True, max_length=80)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FarmerRegistration",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "registration_type",
                    models.CharField(
                        choices=[
                            ("fbo", "FBO / Farmer group"),
                            ("individual", "Individual farmer"),
                        ],
                        default="fbo",
                        max_length=20,
                    ),
                ),
                ("fbo_name", models.CharField(blank=True, max_length=160)),
                ("contact_name", models.CharField(max_length=160)),
                ("phone", models.CharField(db_index=True, max_length=20)),
                ("region", models.CharField(max_length=80)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("member_count", models.CharField(blank=True, max_length=40)),
                ("crops", models.CharField(blank=True, max_length=400)),
                ("typical_quantity", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("available", "Available"),
                            ("matched", "Matched"),
                            ("sold", "Sold"),
                            ("managed", "Managed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Farmer registration",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("crop_type", models.CharField(max_length=80)),
                ("description", models.TextField(blank=True)),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("unit", models.CharField(default="crate", max_length=40)),
                ("quantity_available", models.PositiveIntegerField(default=0)),
                ("sold_quantity", models.PositiveIntegerField(default=0)),
                ("min_order", models.PositiveIntegerField(default=1)),
                ("region", models.CharField(max_length=80)),
                (
                    "fbo_source",
                    models.CharField(
                        blank=True, max_length=160, verbose_name="FBO / farm source"
                    ),
                ),
                (
                    "farmer_phone",
                    models.CharField(
                        blank=True,
                        help_text="Phone used by farmers to look up this listing.",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("sold_out", "Sold out"),
                            ("out_of_stock", "Out of stock"),
                            ("hidden", "Hidden"),
                            ("preorder", "Preorder"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("is_preorder", models.BooleanField(default=False)),
                ("available_date", models.DateField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, upload_to="products/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(db_index=True, max_length=255)),
                (
                    "viewed_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                ("count", models.PositiveIntegerField(default=1)),
            ],
            options={
                "ordering": ["-viewed_on", "-count"],
                "unique_together": {("path", "viewed_on")},
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "order_ref",
                    models.CharField(db_index=True, max_length=32, unique=True),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("product_unit", models.CharField(blank=True, max_length=40)),
                ("buyer_name", models.CharField(max_length=160)),
                ("buyer_phone", models.CharField(db_index=True, max_length=20)),
                ("buyer_email", models.EmailField(blank=True, max_length=254)),
                ("quantity", models.PositiveIntegerField()),
                (
                    "price_per_unit",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "delivery_fee",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("total_price", models.DecimalField(decimal_places=2, max_digits=12)),
                ("delivery_address", models.TextField()),
                ("delivery_region", models.CharField(max_length=80)),
                ("order_type", models.CharField(default="direct", max_length=20)),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("payment_ref", models.CharField(blank=True, max_length=80)),
                ("payment_method", models.CharField(default="paystack", max_length=40)),
                ("notes", models.TextField(blank=True)),
                (
                    "order_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("dispatched", "Dispatched"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="marketplace.product",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
