# Generated by Django 5.2.17 on 2026-09-22 23:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Crop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("availability_window_start", models.CharField(max_length=40)),
                ("availability_window_end", models.CharField(max_length=40)),
                ("grade_notes", models.TextField(blank=True)),
                ("pilot", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="FAQ",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=220)),
                ("answer", models.TextField()),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Partner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("logo", models.ImageField(blank=True, upload_to="partners/")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fbo", "FBO"),
                            ("logistics", "Logistics"),
                            ("payment", "Payment"),
                            ("anchor_buyer", "Anchor buyer"),
                        ],
                        max_length=30,
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=220)),
                ("slug", models.SlugField(unique=True)),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("category", models.CharField(max_length=80)),
                ("featured_image", models.ImageField(blank=True, upload_to="posts/")),
                ("excerpt", models.TextField()),
                ("body", models.TextField()),
                ("author", models.CharField(max_length=160)),
            ],
            options={
                "ordering": ["-date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("period", models.CharField(max_length=80)),
                ("is_current", models.BooleanField(default=False)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(max_length=160)),
                ("background", models.CharField(max_length=240)),
                ("photo", models.ImageField(blank=True, upload_to="team/")),
                ("linkedin_url", models.URLField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=160)),
                ("role", models.CharField(blank=True, max_length=160)),
                ("organisation", models.CharField(blank=True, max_length=160)),
                ("location", models.CharField(blank=True, max_length=160)),
                ("crop", models.CharField(blank=True, max_length=100)),
                ("photo", models.ImageField(blank=True, upload_to="testimonials/")),
                ("quote", models.TextField()),
                (
                    "audience",
                    models.CharField(
                        choices=[("farmer", "Farmer"), ("buyer", "Buyer")],
                        max_length=20,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TractionCounter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label", models.CharField(max_length=120)),
                ("value", models.CharField(blank=True, max_length=80)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
